# Generated by Django 5.0.6 on 2024-05-20 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('ubicacion_actores', models.TextField()),
                ('dialogos', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('guionista', 'Guionista'), ('estandar', 'Estándar')], default='estandar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GuionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('ubicacion_actores', models.JSONField()),
                ('dialogos', models.TextField()),
                ('guion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.guion')),
                ('pose_actores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pose')),
            ],
        ),
        migrations.AddField(
            model_name='guion',
            name='pose_actores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pose'),
        ),
    ]
